# --- Jekyll configuration

# Github sets these, and we can't change them.
safe: true
lsi: false
source: .

# These we can modify.

collections:
    research:
        output: false
    projects:
        output: false
    publications:
        output: false

baseurl:

permalink: pretty

gems:
  - jekyll-sitemap
